### ISSUE TITLE
Potential vulnerabilities in Puppet files: Empty Password

### ISSUE THREAD

**Issue by cantebigene** [alphagov/govuk-puppet#10619]
40 empty passwords were found in 40 different scripts.

Script 1: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_crawler/manifests/init.pp
 - Line [81](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_crawler/manifests/init.pp#L81): `amqp_pass=`

Script 2: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/licensify/manifests/apps/configfile.pp
 - Line [37](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/licensify/manifests/apps/configfile.pp#L37): `mongo_database_auth_password=`

Script 3: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_pgbouncer/manifests/db.pp
 - Line [105](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_pgbouncer/manifests/db.pp#L105): `password=`

Script 4: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/whitehall_run_broken_link_checker.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/whitehall_run_broken_link_checker.pp#L18): `icinga::passive_check=`

Script 5: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/enhanced_ecommerce_search_api.pp
 - Line [28](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/enhanced_ecommerce_search_api.pp#L28): `icinga::passive_check=`

Script 6: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/data_sync_complete_staging.pp
 - Line [38](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/data_sync_complete_staging.pp#L38): `icinga::passive_check=`

Script 7: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/transition_import_hits.pp
 - Line [26](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/transition_import_hits.pp#L26): `icinga::passive_check=`

Script 8: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/publishing_api_archive_events.pp
 - Line [21](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/publishing_api_archive_events.pp#L21): `icinga::passive_check=`

Script 9: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/bouncer_cdn.pp
 - Line [32](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/bouncer_cdn.pp#L32): `icinga::passive_check=`

Script 10: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/content_data_api.pp
 - Line [27](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/content_data_api.pp#L27): `icinga::passive_check=`

Script 11: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/check_cdn_ip_ranges.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/check_cdn_ip_ranges.pp#L19): `icinga::passive_check=`

Script 12: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_api_fetch_analytics_data.pp
 - Line [24](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_api_fetch_analytics_data.pp#L24): `icinga::passive_check=`

Script 13: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_relevancy_rank_evaluation.pp
 - Line [27](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_relevancy_rank_evaluation.pp#L27): `icinga::passive_check=`

Script 14: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_relevancy_metrics_etl.pp
 - Line [28](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_relevancy_metrics_etl.pp#L28): `icinga::passive_check=`

Script 15: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/copy_data_to_integration.pp
 - Line [30](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/copy_data_to_integration.pp#L30): `icinga::passive_check=`

Script 16: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/validate_published_dns.pp
 - Line [23](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/validate_published_dns.pp#L23): `icinga::passive_check=`

Script 17: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/copy_data_to_staging.pp
 - Line [30](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/copy_data_to_staging.pp#L30): `icinga::passive_check=`

Script 18: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_api_reindex_with_new_schema.pp
 - Line [25](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_api_reindex_with_new_schema.pp#L25): `icinga::passive_check=`

Script 19: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/check_sentry_errors.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/check_sentry_errors.pp#L19): `icinga::passive_check=`

Script 20: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/sync_assets_s3.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/sync_assets_s3.pp#L18): `icinga::passive_check=`

Script 21: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_generate_sitemaps.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/search_generate_sitemaps.pp#L18): `icinga::passive_check=`

Script 22: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/check_github_ip_ranges.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/jobs/check_github_ip_ranges.pp#L19): `icinga::passive_check=`

Script 23: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/app/envvar/mongodb_uri.pp
 - Line [26](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/app/envvar/mongodb_uri.pp#L26): `password=`

Script 24: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/specialist_publisher.pp
 - Line [108](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/specialist_publisher.pp#L108): `mongodb_password=`

Script 25: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/bouncer.pp
 - Line [38](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/bouncer.pp#L38): `db_password=`

Script 26: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/maslow.pp
 - Line [49](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/maslow.pp#L49): `mongodb_password=`

Script 27: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/short_url_manager.pp
 - Line [77](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/short_url_manager.pp#L77): `mongodb_password=`

Script 28: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/router_api.pp
 - Line [47](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/router_api.pp#L47): `mongodb_password=`

Script 29: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/travel_advice_publisher.pp
 - Line [81](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/travel_advice_publisher.pp#L81): `mongodb_password=`

Script 30: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/publisher.pp
 - Line [116](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/publisher.pp#L116): `mongodb_password=`

Script 31: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/router.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/router.pp#L18): `mongodb_password=`

Script 32: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/asset_manager.pp
 - Line [69](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/asset_manager.pp#L69): `mongodb_password=`

Script 33: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/manuals_publisher.pp
 - Line [84](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/manuals_publisher.pp#L84): `mongodb_password=`

Script 34: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/transition/postgresql_db.pp
 - Line [20](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/transition/postgresql_db.pp#L20): `password=`

Script 35: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/whitehall/db.pp
 - Line [4](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/whitehall/db.pp#L4): `whitehall_fe_password=`

Script 36: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/bouncer/postgresql_role.pp
 - Line [3](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/bouncer/postgresql_role.pp#L3): `password=`

Script 37: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_mysql_502262ba5e81287d361a84281c3386801c45d6df.pp
 - Line [25](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_mysql_502262ba5e81287d361a84281c3386801c45d6df.pp#L25): `mysql_replica_password=`

Script 38: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/config.pp
 - Line [22](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/config.pp#L22): `http_password=`

Script 39: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/plugin/check_rabbitmq_consumers.pp
 - Line [6](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/plugin/check_rabbitmq_consumers.pp#L6): `monitoring_password=`

Script 40: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/plugin/check_rabbitmq_messages.pp
 - Line [7](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/plugin/check_rabbitmq_messages.pp#L7): `monitoring_password=`

An empty password is a string of length zero. It can be an indicator of a weak password and make the password guessing easier.

This type of smell can lead to a well-known type of vulnerability, as documented by CWE ([CWE-258](https://cwe.mitre.org/data/definitions/258.html)). Empty passwords can be used to gain privileges on applications and access to sensitive data. 

Storing/configuring empty passwords in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
You can replace your empty password with a stronger one. For instance, replace `$password = ’’` by `$password = ‘a!s@d#f$20’`. Be aware that storing passwords in Puppet configuration files is also considered a security smell  (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]). In order to protect/manage your password, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your password by a variable from the vault. For instance, replace`$password = ‘a!s@d#f$20’` by `$password = $vault::password`. Thus, your password will no longer be weak and disclosed publicly.

**Comment by issyl0** [comment]
This does not constitute a vulnerability. In fact, it is surely better than having secrets in plain text in a public repo, as #10618 reported.

If you find any actual security problems in the future, please disclose them _responsibly_ (not in public GitHub issues) by following our [security policy](https://github.com/alphagov/.github/blob/master/SECURITY.md).
