### ISSUE TITLE
Potential vulnerabilities in Puppet files: Invalid IP address binding

### ISSUE THREAD

**Issue by cantebigene** [alphagov/govuk-puppet#10624]
10 cases of invalid IP address binding were found in 10 different scripts.

Script 1: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/licensify/manifests/apps/licensify.pp
 - Line [62](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/licencefinder.pp#L62): `set_real_if_from 0.0.0.0/0`

Script 2: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_mysql/manifests/server.pp
 - Line [84](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_mysql/manifests/server.pp#L84): `0.0.0.0`

Script 3: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_backend.pp
 - Line [42](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_backend.pp#L42): `0.0.0.0`

Script 4: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_calculators_frontend.pp
 - Line [13](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_calculators_frontend.pp#L13): `0.0.0.0`

Script 5: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_publishing_api.pp
 - Line [32](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_publishing_api.pp#L32): `0.0.0.0`

Script 6: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_asset_base.pp
 - Line [152](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_asset_base.pp#L152): `/mnt/uploads     10.0.0.0/8(rw,fsid=0,insecure,no_subtree_check,async,all_squash,anonuid=2900,anongid=2900)`

Script 7: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_whitehall_backend.pp
 - Line [37](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_whitehall_backend.pp#L37): `0.0.0.0`

Script 8: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_frontend.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_frontend.pp#L19): `0.0.0.0`

Script 9: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_whitehall_frontend.pp
 - Line [22](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_whitehall_frontend.pp#L22): `0.0.0.0`

Script 10: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_containers/manifests/etcd.pp
 - Line [23](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_containers/manifests/etcd.pp#L23): `etcd --listen-client-urls "http://0.0.0.0:2379" --advertise-client-urls "http://0.0.0.0:2379"`

An invalid IP address binding is when the 0.0.0.0 address is assigned to a database server or cloud service. 

This type of smell can lead to a well-known type of vulnerability, as documented by CWE ([CWE-284](https://cwe.mitre.org/data/definitions/284.html)). Binding the 0.0.0.0 address to a server/service may allow connections from every possible network because such server/service will be exposed to all IP addresses for connection.

Assigning an invalid IP address binding in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
You can mitigate this by restricting incoming and outgoing connections to a certain IP address and port. For instance, replace `$bind_host = ‘0.0.0.0’` by `$bind_host = ‘127.0.0.1’`. Thus, you will restrict improper access control to your application.

**Comment by cantebigene** [comment]
Script 1 is missing the line number and code. The correct line is the [62](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/licencefinder.pp#L62) and the code is `set_real_if_from 0.0.0.0/0`

**Comment by issyl0** [comment]
If you find any actual security problems in the future, please disclose them _responsibly_ (not in public GitHub issues) by following our [security policy](https://github.com/alphagov/.github/blob/master/SECURITY.md).
