### ISSUE TITLE
Potential vulnerabilities in Puppet files: Use of HTTP without TLS

### ISSUE THREAD

**Issue by cantebigene** [alphagov/govuk-puppet#10620]
88 configurations of HTTP without TLS were found in 62 different scripts.

Script 1: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_postgresql/manifests/mirror.pp
 - Line [11](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_postgresql/manifests/mirror.pp#L11): `http://`

Script 2: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/puppet/manifests/repository.pp
 - Line [34](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/puppet/manifests/repository.pp#L34): `http://`
 - Line [41](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/puppet/manifests/repository.pp#L41): `http://apt.puppetlabs.com`

Script 3: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_ci/manifests/agent.pp
 - Line [15](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_ci/manifests/agent.pp#L15): `http://gemstash.cluster`

Script 4: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_ci/manifests/agent/gcloud.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_ci/manifests/agent/gcloud.pp#L18): `http://`

Script 5: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_sysdig/manifests/init.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_sysdig/manifests/init.pp#L18): `http://`

Script 6: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_java/manifests/repo.pp
 - Line [12](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_java/manifests/repo.pp#L12): `http://`

Script 7: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nodejs/manifests/repo.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nodejs/manifests/repo.pp#L19): `http://`

Script 8: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_rbenv/manifests/all.pp
 - Line [22](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_rbenv/manifests/all.pp#L22): `http://`

Script 9: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_rabbitmq/manifests/repo.pp
 - Line [16](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_rabbitmq/manifests/repo.pp#L16): `http://`

Script 10: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_gor/manifests/init.pp
 - Line [39](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_gor/manifests/init.pp#L39): `http://`

Script 11: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_prometheus/manifests/init.pp
 - Line [26](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_prometheus/manifests/init.pp#L26): `http://`

Script 12: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_awscloudwatch/manifests/init.pp
 - Line [20](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_awscloudwatch/manifests/init.pp#L20): `http://`

Script 13: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/init.pp
 - Line [47](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/init.pp#L47): `http://127.0.0.234/nginx_status`

Script 14: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/package.pp
 - Line [29](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/package.pp#L29): `http://`
 - Line [38](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/package.pp#L38): `http://`

Script 15: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/config/vhost/proxy.pp
 - Line [116](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/nginx/manifests/config/vhost/proxy.pp#L116): `http://`

Script 16: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_unattended_reboot/manifests/repo.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_unattended_reboot/manifests/repo.pp#L18): `http://`

Script 17: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_mysql/manifests/xtrabackup/packages.pp
 - Line [32](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_mysql/manifests/xtrabackup/packages.pp#L32): `http://`
 - Line [43](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_mysql/manifests/xtrabackup/packages.pp#L43): `http://`

Script 18: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_bouncer/manifests/gor.pp
 - Line [23](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_bouncer/manifests/gor.pp#L23): `http://`

Script 19: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/backup/manifests/repo.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/backup/manifests/repo.pp#L18): `http://`

Script 20: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/collectd/manifests/package.pp
 - Line [29](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/collectd/manifests/package.pp#L29): `http://`

Script 21: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/collectd/manifests/plugin/elasticsearch.pp
 - Line [23](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/collectd/manifests/plugin/elasticsearch.pp#L23): `http://`

Script 22: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_prometheus_node_exporter/manifests/repo.pp
 - Line [21](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_prometheus_node_exporter/manifests/repo.pp#L21): `http://`

Script 23: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/statsd/manifests/repo.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/statsd/manifests/repo.pp#L18): `http://`

Script 24: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/datasources.pp
 - Line [31](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/datasources.pp#L31): `http://`
 - Line [37](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/datasources.pp#L37): `http://`
 - Line [54](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/datasources.pp#L54): `http://`
 - Line [60](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/datasources.pp#L60): `http://`

Script 25: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/repo.pp
 - Line [16](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/grafana/manifests/repo.pp#L16): `http://`

Script 26: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/job_builder.pp
 - Line [39](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/job_builder.pp#L39): `http://localhost:8080/`

Script 27: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/job_builder_update.pp
 - Line [13](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/job_builder_update.pp#L13): `http://localhost:8080/`

Script 28: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/cli.pp
 - Line [33](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/cli.pp#L33): `http://localhost:8080/jnlpjars/jenkins-cli.jar`

Script 29: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/package.pp
 - Line [37](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/package.pp#L37): `http://`

Script 30: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/sops.pp
 - Line [20](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/sops.pp#L20): `http://`

Script 31: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/terraform.pp
 - Line [20](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/terraform.pp#L20): `http://`

Script 32: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/gcloud.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/gcloud.pp#L19): `http://`

Script 33: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/govuk_python.pp
 - Line [22](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_jenkins/manifests/packages/govuk_python.pp#L22): `http://`

Script 34: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_solr6/manifests/core.pp
 - Line [23](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_solr6/manifests/core.pp#L23): `test \"$(curl -sl -w '%{http_code}' 'http://`
 - Line [26](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_solr6/manifests/core.pp#L26): `test \"$(curl -sl -w '%{http_code}' 'http://`

Script 35: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_solr6/manifests/repo.pp
 - Line [16](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_solr6/manifests/repo.pp#L16): `http://`

Script 36: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/app/config.pp
 - Line [310](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/app/config.pp#L310): ` {\n  proxy_pass http://`

Script 37: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/whitehall.pp
 - Line [270](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/whitehall.pp#L270): ` {\n  proxy_pass http://`
 - Line [340](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/whitehall.pp#L340): ` {\n  proxy_pass http://`

Script 38: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/canary_backend.pp
 - Line [29](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/canary_backend.pp#L29): `location /_healthcheck_canary-backend {\n  proxy_pass http://localhost/healthcheck;\n  proxy_set_header host canary-backend;\n}\n`

Script 39: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/licencefinder.pp
 - Line [35](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/licencefinder.pp#L35): `http://elasticsearch6`

Script 40: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/content_data_admin.pp
 - Line [140](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/content_data_admin.pp#L140): ` {\n  proxy_pass http://content-data-proxy/healthcheck;\n}\n`

Script 41: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/authenticating_proxy.pp
 - Line [49](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/authenticating_proxy.pp#L49): `http://localhost:3054`

Script 42: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/ckan/cronjobs.pp
 - Line [47](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/apps/ckan/cronjobs.pp#L47): ` -u http://localhost:`

Script 43: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_content_data_api_db_admin.pp
 - Line [57](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_content_data_api_db_admin.pp#L57): `http://`

Script 44: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_licensing_backend.pp
 - Line [41](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_licensing_backend.pp#L41): `http://`
 - Line [49](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_licensing_backend.pp#L49): `http://`

Script 45: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_graphite.pp
 - Line [126](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_graphite.pp#L126): `http://`

Script 46: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_licensing_frontend.pp
 - Line [39](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_licensing_frontend.pp#L39): `http://`
 - Line [47](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_licensing_frontend.pp#L47): `http://`

Script 47: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_transition_db_admin.pp
 - Line [30](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_transition_db_admin.pp#L30): `http://`

Script 48: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_gatling.pp
 - Line [93](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_gatling.pp#L93): `http://`

Script 49: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_db_admin.pp
 - Line [34](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_db_admin.pp#L34): `http://`
 - Line [42](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_db_admin.pp#L42): `http://`
 - Line [91](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_db_admin.pp#L91): `http://`

Script 50: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp
 - Line [45](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L45): `http://repo.aptly.info`
 - Line [49](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L49): `http://ppa.launchpad.net/duplicity-team/ppa/ubuntu`
 - Line [58](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L58): `http://ppa.launchpad.net/gds/govuk/ubuntu`
 - Line [66](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L66): `http://downloads-distro.mongodb.org/repo/ubuntu-upstart`
 - Line [87](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L87): `http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/`
 - Line [91](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L91): `http://repo.percona.com/apt`
 - Line [95](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L95): `http://apt.postgresql.org/pub/repos/apt/`
 - Line [99](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L99): `http://apt.puppetlabs.com/`
 - Line [104](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L104): `http://apt.puppetlabs.com/`
 - Line [109](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L109): `http://www.rabbitmq.com/debian`
 - Line [113](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/node/s_apt.pp#L113): `http://download.draios.com/stable/deb`

Script 51: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/deploy/setup.pp
 - Line [17](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk/manifests/deploy/setup.pp#L17): `http://gemstash.cluster`

Script 52: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_splunk/manifests/repos.pp
 - Line [22](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_splunk/manifests/repos.pp#L22): `http://`
 - Line [29](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_splunk/manifests/repos.pp#L29): `http://`

Script 53: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/config.pp
 - Line [84](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/icinga/manifests/config.pp#L84): `http://`

Script 54: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_ppa/manifests/init.pp
 - Line [44](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_ppa/manifests/init.pp#L44): `http://`

Script 55: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_docker/manifests/repo.pp
 - Line [16](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_docker/manifests/repo.pp#L16): `http://`

Script 56: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_awscli/manifests/init.pp
 - Line [20](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_awscli/manifests/init.pp#L20): `http://`

Script 57: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_beat/manifests/repo.pp
 - Line [16](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_beat/manifests/repo.pp#L16): `http://`

Script 58: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/gdal/manifests/repo.pp
 - Line [16](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/gdal/manifests/repo.pp#L16): `http://`

Script 59: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_containers/manifests/etcd.pp
 - Line [23](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_containers/manifests/etcd.pp#L23): `etcd --listen-client-urls "http://0.0.0.0:2379" --advertise-client-urls "http://0.0.0.0:2379"`

Script 60: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/yarn/manifests/repo.pp
 - Line [18](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/yarn/manifests/repo.pp#L18): `http://`

Script 61: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_bundler/manifests/config.pp
 - Line [19](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/govuk_bundler/manifests/config.pp#L19): `http://gemstash.cluster`

Script 62: https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/mongodb/manifests/repository.pp
 - Line [27](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/mongodb/manifests/repository.pp#L27): `http://`
 - Line [35](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/mongodb/manifests/repository.pp#L35): `http://`
 - Line [43](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/mongodb/manifests/repository.pp#L43): `http://`
 - Line [52](https://github.com/alphagov/govuk-puppet/blob/502262ba5e81287d361a84281c3386801c45d6df/modules/mongodb/manifests/repository.pp#L52): `http://downloads-distro.mongodb.org/repo/ubuntu-upstart`

This type of smell can lead to a well-known type of vulnerability, as documented by CWE ([CWE-546](https://cwe.mitre.org/data/definitions/546.html)). Using HTTP without TLS to communicate with other servers/sources gives access to sensitive or security-critical data in cleartext to unauthorized actors during network communication/traffic (e.g., man-in-the-middle attacks).

Configuring HTTP without using TLS in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
You can instead use HTTPS (HTTP using TLS) to protect the privacy and integrity of the exchanged data. For instance, replace `$auth_url = ‘http://127.0.0.1:35357/’` by `$auth_url = ‘https://127.0.0.1:35357/’`. Thus, you will highly decrease the chances of having your app data leaked.

**Comment by issyl0** [comment]
If you find any actual security problems in the future, please disclose them _responsibly_ (not in public GitHub issues) by following our [security policy](https://github.com/alphagov/.github/blob/master/SECURITY.md).
