### ISSUE TITLE
Public visibility of https://github.com/alphagov/govuk-puppet/blob/main/hieradata_aws/vagrant_credentials.yaml

### ISSUE THREAD

**Issue by annaobarz** [alphagov/govuk-puppet#12155]
I stumbled across this publicly accessible page, and was wondering whether it should be publicly accessible?

**Comment by sengi** [comment]
I think the Vagrant environment hasn't been used in a long time and this is some disused config related to it, but we really appreciate your vigilance — thanks for raising this!

I'll double-check that those private keys etc. really aren't used anywhere. (And of course we'll nuke the file in the meantime.)

**Comment by sengi** [comment]
Also huge thanks for putting me onto the fact that — somehow — we don't appear to have secret scanning enabled on this repo 😅 (it's supposed to be enabled+enforced org-wide, plus I thought public repos were meant to be covered by default — clearly not always, apparently!)

**Comment by annaobarz** [comment]
@sengi happy to help!
