### ISSUE TITLE
Node definitions don't need to be prefixed with `s_`

### ISSUE THREAD

**Issue by alexmuller** [alphagov/govuk-puppet#2923]
Does anyone know why they are? c41e32d75d5002feef14308c006f7bb8d198a07d is the relevant commit.

**Comment by nickstenning** [comment]
> Licensify is a good example of this. The licensify module contains manifests with all of the resources needed to run Licensify. If we were to call the node definition licensify, too, when the catalogue compiled, we'd get duplicate declaration errors and it would probably fail to compile the catalogue and thus refuse to properly run.

It's been a long time, but I'm pretty sure this is the reason we did this.
