### ISSUE TITLE
Provisioning monitoring box fails

### ISSUE THREAD

**Issue by alexmuller** [alphagov/govuk-puppet#3096]
See: #2854

> The problem is that the host directory (/etc/icinga/conf.d/host_foo-host-1) is removed by Puppet and then no check files (/etc/icinga/conf.d/host_foo-host-1/my_check.cfg) can be written.
> 
> The problem can be replicated by bringing up a fresh monitoring box. The problem can be fixed by using this pull request, but clearly this is not a change we want to make.

**Comment by djsd123** [comment]
This is still an issue

**Comment by tijmenb** [comment]
I'm going to close this, as the issues on GitHub are not a backlog and the issue doesn't give us more information about the solution. The move to AWS might fix this by itself as well.
