### ISSUE TITLE
govuk_app_console does not set correct env vars for publishing-api in development VM

### ISSUE THREAD

**Issue by rubenarakelyan** [alphagov/govuk-puppet#5065]
Running `govuk_app_console publishing-api` sets the relevant env vars for the Postgres role to "deploy" rather than "vagrant" when running in the development VM. This means that any actions in the console that rely on the database fail.

The workaround is to run `bundle exec rails console` instead, but it would be good to get this to work consistently.

I have opened this issue as I cannot see exactly where this env var is set from.

**Comment by brenetic** [comment]
@rubenarakelyan Seems to be hardcoded in `modules/govuk_scripts/files/usr/local/bin/govuk_app_console`
