### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by bruth** [alphagov/govuk-puppet#5244]
I am not sure why, but I am getting email notifications from `webops+ci@digital.cabinet-office.gov.uk`.

**Comment by alexmuller** [comment]
Hi - sorry about that. Is it possible that your email address is in the git commit history for this repository? If you can forward the email to me (alex.muller@digital.cabinet-office.gov.uk) that would be great. Thanks!

**Comment by alexmuller** [comment]
Got some details from @bruth and I think I've figured out what happened - it's completely ridiculous but it's the only explanation I can come up with.

I think in March 2015 Matt was doing some work with the opsmanual which used [bruth/jekyll-docs-template](https://github.com/bruth/jekyll-docs-template/) which resulted in [this build](https://ci.dev.publishing.service.gov.uk/job/opsmanual_branches/205/).

Jenkins saw those commits and created a person on disk called `b` with @bruth's email address attached to it.

Recently @brenetic changed his email address to be `b@brenetic.com`. Every time @brenetic pushes a commit which fails tests, Jenkins decides that this person with a `b` email address is probably the same `b` that it already knows about and emails @bruth with the test results.

Argh! Sorry again for the problems.
