### ISSUE TITLE
Incorrect proxy destination for publicapi

### ISSUE THREAD

**Issue by rubenarakelyan** [alphagov/govuk-puppet#6059]
The default proxy destination of `publicapi` (as defined in https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/apps/publicapi.pp#L38) is three subdomains that represent three different apps (whitehall, content-store and rummager). This is incorrect since an array of destinations denotes round-robin load balancing which doesn't make sense if you're balancing between different apps.

The more specific location blocks in the config actually take care of all traffic routing so this error doesn't cause any issues, but since it also doesn't get any traffic it should probably be removed altogether.

**Comment by MatMoore** [comment]
Did we ever fix this?

**Comment by rubenarakelyan** [comment]
Nope, AFAIK it's still like that. I think we should remove the round-robin stuff and just have location blocks for the various apps but it needs to be tested to make sure we don't break the public API.

**Comment by MatMoore** [comment]
Yep. Could maybe do it as a firebreak task if it doesn't fit on the platform health backlog.

**Comment by tijmenb** [comment]
All of the routing is now done via the publishing-api/router and publicapi has been retired (https://github.com/alphagov/govuk-puppet/pull/8637). Closing!
