### ISSUE TITLE
Incorrect file permissions for Ruby

### ISSUE THREAD

**Issue by theseanything** [alphagov/govuk-puppet#8128]
When setting up a brand new VM I experience the follow issues.
Running `./update-bundler.sh` fails to run with the following error for some repos:
```
Errno::EPERM: Operation not permitted @ chown_internal -
/tmp/bundler20180918-9784-17s3u11rake-12.3.1/bin
```
Running `bundle install` in some repos produces:
```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/lib/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0 directory.
```
It appears the `/usr/lib/rbenv/versions/` is owned by `root:root`
The errors are  fixed when changing permissions:
```
sudo chown vagrant -R /usr/lib/rbenv/versions/
sudo chgrp vagrant -R /usr/lib/rbenv/versions/
```

**Comment by thomasleese** [comment]
There are some docs about this problem: https://docs.publishing.service.gov.uk/manual/gem-file-permission-errors.html

Although it suggests an alternative solution, maybe the docs need updating?

**Comment by ChrisBAshton** [comment]
FWIW, I think I had to do the same thing (`sudo chown vagrant -R /usr/lib/rbenv/versions/`).

**Comment by tijmenb** [comment]
Let's close this, as we are focusing our development efforts on https://github.com/alphagov/govuk-docker.
