### ISSUE TITLE
Remove bootstrap.sh

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-puppet#9130]
It doesn't look like this is actually used? https://github.com/alphagov/govuk-puppet/blob/master/development-vm/bootstrap.sh

It isn't mentioned anywhere in the getting started instructions: https://docs.publishing.service.gov.uk/manual/get-started.html#4-boot-your-vm

And it was last updated 3 years ago.

Can it be safely removed?

**Comment by tijmenb** [comment]
Yes, go ahead 👍
